global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus tự giám sát
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Giám sát ứng dụng Web Quản lý Sinh viên (Node.js Express /metrics)
  - job_name: 'student-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
        labels:
          environment: 'production'
          service: 'student-management-app'

  # 3. Giám sát tài nguyên Containers qua cAdvisor (CPU, RAM, Network I/O)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container-metrics'

  # 4. Giám sát Cơ sở dữ liệu MySQL 8.0 qua mysqld-exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          service: 'database-metrics'
